power <- read.csv("household_power_consumption.txt", header=TRUE, stringsAsFactors = FALSE, sep=";")
  Date_Time <- vector()
  Date_Time <- paste(power$Date, " ", power$Time)
  Date_Time <- strptime(Date_Time, format = "%d/%m/%Y %H:%M:%S")
  Date_Time <- as.POSIXlt(Date_Time)
power <- data.frame(Date_Time, power[, c(3:9)])
power <- subset(power, power[, 1] >= "2007-02-01 00:00:00" & power[, 1] < "2007-02-03 00:00:00")
  power$Global_active_power <- as.numeric(power$Global_active_power)
  power$Global_reactive_power <- as.numeric(power$Global_reactive_power)
  power$Voltage <- as.numeric(power$Voltage)
  power$Global_intensity <- as.numeric(power$Global_intensity)
  power$Sub_metering_1 <- as.numeric(power$Sub_metering_1)
  power$Sub_metering_2 <- as.numeric(power$Sub_metering_2)
  power$Sub_metering_3 <- as.numeric(power$Sub_metering_3)
windows()
  par(mfcol = c(2, 2), mar = c(4, 4, 2, 2))
    plot(power$Date_Time, power$Global_active_power, type = "o", pch = "", xlab = "", ylab = "Global Active Power (kilowatts)")
    plot(power$Date_Time, power$Sub_metering_1, type = "n", xlab = "", ylab = "Energy Sub Metering")
      points(power$Date_Time, power$Sub_metering_1, type = "o", pch = "")
      points(power$Date_Time, power$Sub_metering_2, type = "o", pch = "", col = "red")
      points(power$Date_Time, power$Sub_metering_3, type = "o", pch = "", col = "blue")
      legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1, 1, 1), col = c("black", "red", "blue"))
    plot(power$Date_Time, power$Voltage, type = "o", pch = "", xlab = "", ylab = "Voltage")
    plot(power$Date_Time, power$Global_reactive_power, type = "o", pch = "", xlab = "", ylab = "Global Reactive Power")
  dev.copy(png, "plot4.png")
dev.off()
