power <- read.csv("household_power_consumption.txt", header=TRUE, stringsAsFactors = FALSE, sep=";")
  Date_Time <- vector()
  Date_Time <- paste(power$Date, " ", power$Time)
  Date_Time <- strptime(Date_Time, format = "%d/%m/%Y %H:%M:%S")
  Date_Time <- as.POSIXlt(Date_Time)
power <- data.frame(Date_Time, power[, c(3:9)])
power <- subset(power, power[, 1] >= "2007-02-01 00:00:00" & power[, 1] < "2007-02-03 00:00:00")
  power$Global_active_power <- as.numeric(power$Global_active_power)
  power$Global_reactive_power <- as.numeric(power$Global_reactive_power)
  power$Voltage <- as.numeric(power$Voltage)
  power$Global_intensity <- as.numeric(power$Global_intensity)
  power$Sub_metering_1 <- as.numeric(power$Sub_metering_1)
  power$Sub_metering_2 <- as.numeric(power$Sub_metering_2)
  power$Sub_metering_3 <- as.numeric(power$Sub_metering_3)
windows()
  hist(power$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power (Kilowatts)")
  dev.copy(png, "plot1.png")
dev.off()
